version: "3.5"
services:
  nginx:
    container_name: nginx_go_vue3_tsx
    image: nginx:stable-alpine
    restart: on-failure
    depends_on:
      - golang
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/var/www/public:ro
      - ./logs:/var/log/nginx

  golang:
    container_name: golang_go_vue3_tsx
    build: .
    # image: geospatialweb/go-vue3-tsx:latest
    command: /app/main
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - app-network

  postgres:
    container_name: postgis_go_vue3_tsx
    image: kartoza/postgis:12.0
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./postgres/postgis.sql:/docker-entrypoint-initdb.d/postgis.sql
    environment:
      POSTGRES_DBNAME:  ${POSTGRES_DBNAME}
      POSTGRES_PASS:    ${POSTGRES_PASSWORD}
      POSTGRES_USER:    ${POSTGRES_USER}

networks:
  app-network:
    driver: bridge
